const templates = [
  // ============= PREMIUM TEMPLATES (with photo) =============
  {
    id: 'premium-biru',
    name: 'Premium Biru Corporate',
    emoji: '💼',
    width: 500,
    height: 320,
    desc: 'Kartu ID corporate modern dgn foto & gradasi biru',
    hasPhoto: true,
    photoArea: { x: 30, y: 60, width: 85, height: 85, shape: 'roundrect', borderWidth: 2, borderColor: '#ffffff' },
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA KARYAWAN', x: 140, y: 75, fontSize: 22, fontWeight: 'bold', fill: '#1a365d', fontFamily: 'Inter', textAlign: 'left' },
      { key: 'jabatan', label: 'Jabatan', value: 'KASIR', x: 140, y: 105, fontSize: 14, fontWeight: '600', fill: '#2563eb', fontFamily: 'Inter', textAlign: 'left' },
      { key: 'nik', label: 'NIK', value: 'IDM-2024-XXXX', x: 140, y: 130, fontSize: 11, fontWeight: 'normal', fill: '#64748b', fontFamily: 'Inter', textAlign: 'left', prefix: 'NIK: ' },
      { key: 'divisi', label: 'Divisi', value: 'DIVISI', x: 140, y: 150, fontSize: 11, fontWeight: 'normal', fill: '#64748b', fontFamily: 'Inter', textAlign: 'left', prefix: 'Divisi: ' },
      { key: 'kode_toko', label: 'Kode Toko', value: 'IDM-XXXX', x: 140, y: 170, fontSize: 11, fontWeight: 'normal', fill: '#64748b', fontFamily: 'Inter', textAlign: 'left', prefix: 'Toko: ' },
      { key: 'footer', label: 'Footer', value: 'KARYAWAN AKTIF', x: 250, y: 290, fontSize: 10, fontWeight: '600', fill: '#94a3b8', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 500, height: 35, fill: '#1a365d' },
      { type: 'headerText', x: 250, y: 17, text: 'KARTU IDENTITAS KARYAWAN', fontSize: 13, fontWeight: 'bold', fill: '#ffffff', fontFamily: 'Inter', textAlign: 'center' },
      { type: 'accentLine', x: 0, y: 0, width: 5, height: 320, fill: '#2563eb' },
      { type: 'footerBar', x: 0, y: 295, width: 500, height: 25, fill: '#f1f5f9' },
      { type: 'separator', x: 130, y: 195, x2: 470, y2: 195, stroke: '#e2e8f0', strokeWidth: 1 },
    ],
    defaultBg: '#ffffff',
    defaultBorder: '#1a365d',
  },
  {
    id: 'premium-hitam-emas',
    name: 'Premium Hitam Emas',
    emoji: '💎',
    width: 500,
    height: 320,
    desc: 'Kartu luxury hitam dgn aksen emas & foto',
    hasPhoto: true,
    photoArea: { x: 30, y: 55, width: 85, height: 85, shape: 'circle', borderWidth: 2.5, borderColor: '#d4af37' },
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA KARYAWAN', x: 140, y: 70, fontSize: 24, fontWeight: 'bold', fill: '#f8fafc', fontFamily: 'Playfair Display', textAlign: 'left' },
      { key: 'jabatan', label: 'Jabatan', value: 'CEO / FOUNDER', x: 140, y: 108, fontSize: 14, fontWeight: '600', fill: '#d4af37', fontFamily: 'Inter', textAlign: 'left' },
      { key: 'nik', label: 'NIK', value: 'EMP-001-XXXX', x: 140, y: 133, fontSize: 11, fontWeight: 'normal', fill: '#94a3b8', fontFamily: 'Inter', textAlign: 'left', prefix: 'ID: ' },
      { key: 'divisi', label: 'Divisi', value: 'MANAGEMENT', x: 140, y: 153, fontSize: 11, fontWeight: 'normal', fill: '#94a3b8', fontFamily: 'Inter', textAlign: 'left', prefix: 'Divisi: ' },
      { key: 'kode_toko', label: 'Kantor', value: 'KANTOR PUSAT', x: 140, y: 173, fontSize: 11, fontWeight: 'normal', fill: '#94a3b8', fontFamily: 'Inter', textAlign: 'left', prefix: 'Lokasi: ' },
      { key: 'footer', label: 'Footer', value: 'KARYAWAN TETAP', x: 250, y: 290, fontSize: 9, fontWeight: '600', fill: '#d4af37', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 500, height: 30, fill: '#d4af37' },
      { type: 'headerText', x: 250, y: 15, text: '★ PREMIUM MEMBER ★', fontSize: 13, fontWeight: 'bold', fill: '#0f0f0f', fontFamily: 'Inter', textAlign: 'center' },
      { type: 'accentLine', x: 0, y: 0, width: 4, height: 320, fill: '#d4af37' },
      { type: 'footerBar', x: 0, y: 295, width: 500, height: 25, fill: 'rgba(212,175,55,0.08)' },
      { type: 'separator', x: 130, y: 198, x2: 470, y2: 198, stroke: 'rgba(212,175,55,0.3)', strokeWidth: 0.5 },
      { type: 'bgAccent', x: 0, y: 30, width: 500, height: 265, fill: '#0f0f0f' },
    ],
    defaultBg: '#0f0f0f',
    defaultBorder: '#d4af37',
  },
  {
    id: 'premium-putih-elegan',
    name: 'Premium Putih Elegan',
    emoji: '✨',
    width: 500,
    height: 320,
    desc: 'Kartu putih minimalis elegan dengan foto kiri',
    hasPhoto: true,
    photoArea: { x: 30, y: 55, width: 82, height: 82, shape: 'roundrect', borderWidth: 1.5, borderColor: '#1e40af' },
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA LENGKAP', x: 135, y: 68, fontSize: 22, fontWeight: 'bold', fill: '#1e293b', fontFamily: 'Plus Jakarta Sans', textAlign: 'left' },
      { key: 'jabatan', label: 'Jabatan', value: 'POSITION / TITLE', x: 135, y: 100, fontSize: 13, fontWeight: '500', fill: '#3b82f6', fontFamily: 'Inter', textAlign: 'left' },
      { key: 'nik', label: 'NIK', value: 'EMP-2024-XXXXX', x: 135, y: 128, fontSize: 10, fontWeight: 'normal', fill: '#64748b', fontFamily: 'Inter', textAlign: 'left', prefix: 'Employee ID: ' },
      { key: 'divisi', label: 'Dept', value: 'DEPARTMENT', x: 135, y: 146, fontSize: 10, fontWeight: 'normal', fill: '#64748b', fontFamily: 'Inter', textAlign: 'left', prefix: 'Dept: ' },
      { key: 'kode_toko', label: 'Branch', value: 'BRANCH / OFFICE', x: 135, y: 164, fontSize: 10, fontWeight: 'normal', fill: '#64748b', fontFamily: 'Inter', textAlign: 'left', prefix: 'Branch: ' },
      { key: 'footer', label: 'Footer', value: 'ACTIVE EMPLOYEE — VALID 2025', x: 250, y: 290, fontSize: 9, fontWeight: '600', fill: '#94a3b8', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 500, height: 4, fill: '#1e40af' },
      { type: 'headerBar2', x: 345, y: 40, width: 125, height: 40, fill: '#1e40af' },
      { type: 'headerText', x: 407, y: 60, text: 'ID CARD', fontSize: 12, fontWeight: 'bold', fill: '#ffffff', fontFamily: 'Inter', textAlign: 'center' },
      { type: 'footerBar', x: 0, y: 295, width: 500, height: 25, fill: '#f8fafc' },
      { type: 'accentLine', x: 0, y: 4, width: 3, height: 291, fill: '#3b82f6' },
      { type: 'separator', x: 125, y: 190, x2: 470, y2: 190, stroke: '#e2e8f0', strokeWidth: 1 },
    ],
    defaultBg: '#ffffff',
    defaultBorder: '#1e40af',
  },
  {
    id: 'premium-hijau-nature',
    name: 'Premium Natural Green',
    emoji: '🌿',
    width: 500,
    height: 320,
    desc: 'Kartu natural green dgn foto circle & layout segar',
    hasPhoto: true,
    photoArea: { x: 30, y: 60, width: 80, height: 80, shape: 'circle', borderWidth: 2, borderColor: '#059669' },
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA KARYAWAN', x: 135, y: 75, fontSize: 21, fontWeight: 'bold', fill: '#14532d', fontFamily: 'DM Sans', textAlign: 'left' },
      { key: 'jabatan', label: 'Jabatan', value: 'STAFF / TEAM LEAD', x: 135, y: 108, fontSize: 13, fontWeight: '500', fill: '#059669', fontFamily: 'DM Sans', textAlign: 'left' },
      { key: 'nik', label: 'NIK', value: 'NAT-001-XXXX', x: 135, y: 133, fontSize: 10, fontWeight: 'normal', fill: '#4a7c59', fontFamily: 'DM Sans', textAlign: 'left', prefix: 'ID: ' },
      { key: 'divisi', label: 'Divisi', value: 'TEAM / DIVISI', x: 135, y: 152, fontSize: 10, fontWeight: 'normal', fill: '#4a7c59', fontFamily: 'DM Sans', textAlign: 'left', prefix: 'Team: ' },
      { key: 'kode_toko', label: 'Lokasi', value: 'LOKASI / CABANG', x: 135, y: 171, fontSize: 10, fontWeight: 'normal', fill: '#4a7c59', fontFamily: 'DM Sans', textAlign: 'left', prefix: 'Lokasi: ' },
      { key: 'footer', label: 'Footer', value: '#GO GREEN  ♻️  KARYAWAN AKTIF', x: 250, y: 292, fontSize: 9, fontWeight: '600', fill: '#6b9b7a', fontFamily: 'DM Sans', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 500, height: 38, fill: '#059669' },
      { type: 'headerText', x: 250, y: 19, text: '🌿 NATURAL WORKS', fontSize: 14, fontWeight: 'bold', fill: '#ffffff', fontFamily: 'DM Sans', textAlign: 'center' },
      { type: 'footerBar', x: 0, y: 295, width: 500, height: 25, fill: '#f0fdf4' },
      { type: 'accentLine', x: 0, y: 38, width: 3, height: 257, fill: '#10b981' },
      { type: 'separator', x: 125, y: 195, x2: 470, y2: 195, stroke: '#bbf7d0', strokeWidth: 1 },
    ],
    defaultBg: '#fafdf6',
    defaultBorder: '#059669',
  },
  {
    id: 'premium-night-elegant',
    name: 'Premium Night Elegant',
    emoji: '🌙',
    width: 500,
    height: 320,
    desc: 'Dark premium dengan glow ungu-biru & foto',
    hasPhoto: true,
    photoArea: { x: 30, y: 55, width: 85, height: 85, shape: 'circle', borderWidth: 2, borderColor: '#8b5cf6' },
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA KARYAWAN', x: 140, y: 72, fontSize: 22, fontWeight: 'bold', fill: '#f8fafc', fontFamily: 'Outfit', textAlign: 'left' },
      { key: 'jabatan', label: 'Jabatan', value: 'POSITION / ROLE', x: 140, y: 108, fontSize: 14, fontWeight: '500', fill: '#a78bfa', fontFamily: 'Outfit', textAlign: 'left' },
      { key: 'nik', label: 'NIK', value: 'NGHT-001-XXXX', x: 140, y: 133, fontSize: 11, fontWeight: 'normal', fill: '#94a3b8', fontFamily: 'Outfit', textAlign: 'left', prefix: 'ID: ' },
      { key: 'divisi', label: 'Divisi', value: 'DIVISION', x: 140, y: 153, fontSize: 11, fontWeight: 'normal', fill: '#94a3b8', fontFamily: 'Outfit', textAlign: 'left', prefix: 'Dept: ' },
      { key: 'kode_toko', label: 'Lokasi', value: 'CABANG / AREA', x: 140, y: 173, fontSize: 11, fontWeight: 'normal', fill: '#94a3b8', fontFamily: 'Outfit', textAlign: 'left', prefix: 'Area: ' },
      { key: 'footer', label: 'Footer', value: '✦ NIGHT TEAM ✦  •  ACTIVE', x: 250, y: 292, fontSize: 9, fontWeight: '600', fill: '#8b5cf6', fontFamily: 'Outfit', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 500, height: 32, fill: '#8b5cf6' },
      { type: 'headerText', x: 250, y: 16, text: '✦ NIGHT ELEGANCE ✦', fontSize: 13, fontWeight: 'bold', fill: '#ffffff', fontFamily: 'Outfit', textAlign: 'center' },
      { type: 'footerBar', x: 0, y: 295, width: 500, height: 25, fill: 'rgba(139,92,246,0.08)' },
      { type: 'accentLine', x: 0, y: 32, width: 3, height: 263, fill: '#8b5cf6' },
      { type: 'separator', x: 130, y: 198, x2: 470, y2: 198, stroke: 'rgba(139,92,246,0.2)', strokeWidth: 0.5 },
      { type: 'bgAccent', x: 0, y: 32, width: 500, height: 263, fill: '#0f0f1a' },
    ],
    defaultBg: '#0f0f1a',
    defaultBorder: '#8b5cf6',
  },
  // ============= CLASSIC TEMPLATES (no photo, smaller) =============
  {
    id: 'indomaret-standar',
    name: 'Indomaret Standar',
    emoji: '🏪',
    width: 400,
    height: 250,
    desc: 'Template putih bersih khas Indomaret',
    hasPhoto: false,
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA KARYAWAN', x: 200, y: 100, fontSize: 26, fontWeight: 'bold', fill: '#1a365d', fontFamily: 'Inter', textAlign: 'center' },
      { key: 'jabatan', label: 'Jabatan', value: 'KASIR', x: 200, y: 140, fontSize: 16, fontWeight: 'normal', fill: '#2d3748', fontFamily: 'Inter', textAlign: 'center' },
      { key: 'kode_toko', label: 'Kode Toko', value: 'IDM-XXXX', x: 200, y: 170, fontSize: 12, fontWeight: 'normal', fill: '#718096', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [],
    defaultBg: '#ffffff',
    defaultBorder: '#1a365d',
  },
  {
    id: 'indomaret-premium',
    name: 'Indomaret Premium',
    emoji: '🔵',
    width: 400,
    height: 250,
    desc: 'Biru elegan dengan teks putih',
    hasPhoto: false,
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA KARYAWAN', x: 200, y: 95, fontSize: 28, fontWeight: 'bold', fill: '#ffffff', fontFamily: 'Inter', textAlign: 'center' },
      { key: 'jabatan', label: 'Jabatan', value: 'KASIR', x: 200, y: 140, fontSize: 16, fontWeight: 'normal', fill: '#e2e8f0', fontFamily: 'Inter', textAlign: 'center' },
      { key: 'kode_toko', label: 'Kode Toko', value: 'IDM-XXXX', x: 200, y: 170, fontSize: 12, fontWeight: 'normal', fill: '#a0aec0', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 400, height: 5, fill: '#2563eb' },
    ],
    defaultBg: '#1a365d',
    defaultBorder: '#2d5280',
  },
  {
    id: 'elegan-hitam',
    name: 'Elegan Hitam Emas',
    emoji: '🖤',
    width: 400,
    height: 250,
    desc: 'Mewah dengan kombinasi hitam & emas',
    hasPhoto: false,
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA', x: 200, y: 100, fontSize: 30, fontWeight: 'bold', fill: '#d4af37', fontFamily: 'Playfair Display', textAlign: 'center' },
      { key: 'jabatan', label: 'Jabatan', value: 'JABATAN', x: 200, y: 140, fontSize: 16, fontWeight: 'normal', fill: '#e2e8f0', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [
      { type: 'headerBar', x: 0, y: 0, width: 400, height: 3, fill: '#d4af37' },
      { type: 'footerBar', x: 0, y: 247, width: 400, height: 3, fill: '#d4af37' },
    ],
    defaultBg: '#0f0f0f',
    defaultBorder: '#d4af37',
  },
  {
    id: 'kotak-modern',
    name: 'Modern Kotak',
    emoji: '📐',
    width: 350,
    height: 200,
    desc: 'Minimalis dengan border tipis',
    hasPhoto: false,
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA', x: 175, y: 85, fontSize: 24, fontWeight: 'bold', fill: '#2d3748', fontFamily: 'Inter', textAlign: 'center' },
      { key: 'jabatan', label: 'Jabatan', value: 'JABATAN', x: 175, y: 125, fontSize: 14, fontWeight: 'normal', fill: '#4a5568', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [],
    defaultBg: '#f7fafc',
    defaultBorder: '#2d3748',
  },
  {
    id: 'putih-biru',
    name: 'Putih Biru Corporate',
    emoji: '📋',
    width: 400,
    height: 250,
    desc: 'Clean corporate look',
    hasPhoto: false,
    defaultTexts: [
      { key: 'nama', label: 'Nama', value: 'NAMA', x: 200, y: 100, fontSize: 26, fontWeight: 'bold', fill: '#1e40af', fontFamily: 'Inter', textAlign: 'center' },
      { key: 'jabatan', label: 'Jabatan', value: 'JABATAN', x: 200, y: 140, fontSize: 15, fontWeight: 'normal', fill: '#475569', fontFamily: 'Inter', textAlign: 'center' },
    ],
    decorations: [],
    defaultBg: '#ffffff',
    defaultBorder: '#1e40af',
  },
]

export default templates
